#include "/Engine/Public/Platform.ush"

StructuredBuffer<uint> BitmaskBrickVoxel;
RWStructuredBuffer<uint> RWBrickData;

uint BrickCount;
uint BitmaskWordsPerBrick;

[numthreads(64, 1, 1)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
    const uint BrickIndex = DispatchThreadId.x;
    if (BrickIndex >= BrickCount)
    {
        return;
    }

    const uint WordStart = BrickIndex * BitmaskWordsPerBrick;
    uint OccupiedFineVoxelCount = 0u;
    [loop]
    for (uint WordOffset = 0; WordOffset < BitmaskWordsPerBrick; ++WordOffset)
    {
        const uint Word = BitmaskBrickVoxel[WordStart + WordOffset];
        OccupiedFineVoxelCount += countbits(Word);
    }

    RWBrickData[BrickIndex * 4u + 0u] = OccupiedFineVoxelCount;
}
