#include "/Engine/Public/Platform.ush"

#include "/InstantRdvShaders/Private/instant_rdv_util.ush"

RWStructuredBuffer<uint> RWBbvBuffer;
RWStructuredBuffer<uint> RWBitmaskBrickVoxelOptionData;

uint BitmaskElementCount;
uint BrickDataElementCount;
uint BrickDataBaseOffset;
uint OptionalDataElementCount;
uint DispatchLinearWidth;
uint DispatchThreadCount;

[numthreads(64, 1, 1)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
    const uint Index = DispatchThreadId.x + DispatchThreadId.y * DispatchLinearWidth;

    for (uint It = Index; It < BitmaskElementCount; It += DispatchThreadCount)
    {
        RWBbvBuffer[It] = 0;
    }

    for (uint It = Index; It < BrickDataElementCount; It += DispatchThreadCount)
    {
        RWBbvBuffer[BrickDataBaseOffset + It] = 0;
    }

    for (uint It = Index; It < OptionalDataElementCount; It += DispatchThreadCount)
    {
        RWBitmaskBrickVoxelOptionData[It] = 0;
    }
}
