#include "/Engine/Public/Platform.ush"

#include "/InstantRdvShaders/Private/instant_rdv_util.ush"

RWStructuredBuffer<uint> RWBbvBuffer;

uint BrickCount;
uint BrickDataBaseOffset;

[numthreads(64, 1, 1)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
    const uint BrickIndex = DispatchThreadId.x;
    if (BrickIndex >= BrickCount)
    {
        return;
    }

	const uint WordStart = BrickIndex * k_irdv_bbv_bitmask_u32_count_per_brick;
    uint OccupiedFineVoxelCount = 0u;
	uint3 LocalCoordMin = uint3(k_irdv_bbv_brick_reso - 1u, k_irdv_bbv_brick_reso - 1u, k_irdv_bbv_brick_reso - 1u);
	uint3 LocalCoordMax = uint3(0u, 0u, 0u);
	[loop]
	for (uint WordOffset = 0; WordOffset < k_irdv_bbv_bitmask_u32_count_per_brick; ++WordOffset)
	{
	    uint Word = RWBbvBuffer[WordStart + WordOffset];
	    OccupiedFineVoxelCount += countbits(Word);
	    while (Word != 0u)
	    {
	        const uint BitIndex = firstbitlow(Word);
	        const uint3 LocalCoord = CalcFineCoordFromBitIndex(WordOffset * 32u + BitIndex);
	        LocalCoordMin = min(LocalCoordMin, LocalCoord);
	        LocalCoordMax = max(LocalCoordMax, LocalCoord);
	        Word &= Word - 1u;
	    }
	}

	const uint BrickDataAddress = BrickDataBaseOffset + BrickIndex * k_irdv_bbv_brick_data_u32_count;
	RWBbvBuffer[BrickDataAddress + 0u] = OccupiedFineVoxelCount;
	if (OccupiedFineVoxelCount != 0u)
	{
	    RWBbvBuffer[BrickDataAddress + 2u] = BbvPackBrickLocalAabbCoord(LocalCoordMin);
	    RWBbvBuffer[BrickDataAddress + 3u] = BbvPackBrickLocalAabbCoord(LocalCoordMax);
	}
	else
	{
	    RWBbvBuffer[BrickDataAddress + 2u] = 0u;
	    RWBbvBuffer[BrickDataAddress + 3u] = 0u;
	}
}
