#include "/Engine/Public/Platform.ush"

#include "/InstantRdvShaders/Private/instant_rdv_util.ush"

RWStructuredBuffer<uint> RWBbvBuffer;

uint BrickCount;
uint BrickDataBaseOffset;

[numthreads(64, 1, 1)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
    const uint BrickIndex = DispatchThreadId.x;
    if (BrickIndex >= BrickCount)
    {
        return;
    }

	const uint WordStart = BrickIndex * k_irdv_bbv_bitmask_u32_count_per_brick;
    uint OccupiedFineVoxelCount = 0u;
    [loop]
	for (uint WordOffset = 0; WordOffset < k_irdv_bbv_bitmask_u32_count_per_brick; ++WordOffset)
    {
        const uint Word = RWBbvBuffer[WordStart + WordOffset];
        OccupiedFineVoxelCount += countbits(Word);
    }

    RWBbvBuffer[BrickDataBaseOffset + BrickIndex * 4u + 0u] = OccupiedFineVoxelCount;
}
