#include "/Engine/Public/Platform.ush"

#include "/InstantRdvShaders/Private/instant_rdv_util.ush"

StructuredBuffer<uint> FrustumBrickCounter;
RWBuffer<uint> RWFrustumBrickIndirectArg;
uint ThreadGroupSizeX;

[numthreads(1, 1, 1)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
    const uint FrustumCount = FrustumBrickCounter[0];
	const uint TotalJobs = FrustumCount * k_irdv_bbv_bitmask_u32_count_per_brick;
    const uint DispatchGroupX = (TotalJobs + ThreadGroupSizeX - 1u) / max(ThreadGroupSizeX, 1u);
    RWFrustumBrickIndirectArg[0] = DispatchGroupX;
    RWFrustumBrickIndirectArg[1] = 1u;
    RWFrustumBrickIndirectArg[2] = 1u;
}
